# Generated by Django 4.2.3 on 2023-07-30 19:06

from django.db import migrations, models
import pereval.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0004_alter_images_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.ImageField(blank=True, null=True, upload_to=pereval.utils.get_path_upload_photos, verbose_name='Изображение'),
        ),
    ]
